# Whether to include a comment with the version of cbindgen used to generate the file
# default: false
include_version = true

# Whether to add a `#pragma once` guard
# default: doesn't emit a `#pragma once`
pragma_once = true

# Whether cbindgen's default C/C++ standard imports should be suppressed. These
# imports are included by default because our generated headers tend to require
# them (e.g. for uint32_t). Currently, the generated imports are:
#
# * for C: <stdarg.h>, <stdbool.h>, <stdint.h>, <stdlib.h>, <uchar.h>
#
# * for C++: <cstdarg>, <cstdint>, <cstdlib>, <new>, <cassert> (depending on config)
#
# default: false
no_includes = true

# A list of sys headers to #include (with angle brackets)
# default: []
sys_includes = ["cstdint"]

# An optional list of namespaces to output around the generated bindings
# default: []
namespaces = ["ha", "fx_collection_rs", "trance_gate"]
